Ar 41 status recipe
flavor-receitinhas/receitinhas_api pull request #3
Opened 2024-02-23 21:35 UTC by lucascardo12

2024-02-24 18:11 UTC, BrunoAlm approved these changes
perfilzinho top

2024-02-24 18:22 UTC, cledsonv requested changes

2024-02-24 18:22 UTC, cledsonv commented on src/main/resources/application.properties
> +sentry.dsn=https://d66543b55c858858aca35375769efd1d@o4506780583985152.ingest.sentry.io/4506780585426944
Pode estar publico isso aqui?

2024-02-24 18:22 UTC, cledsonv commented on src/main/kotlin/com/flavor/recipes/recipe/entities/RecipeStatus.kt
> +    draft, published, removed
Em vez de removido , poderia ser bloqueado , acho que faz mais sentido

2024-03-01 12:19 UTC, BrunoAlm commented on src/main/kotlin/com/flavor/recipes/recipe/entities/RecipeStatus.kt
> +    draft, published, removed
Por que bloqueado? Se o que o cara vai fazer é excluir a receita

2024-04-12 00:26 UTC, lucascardo12 commented on src/main/kotlin/com/flavor/recipes/recipe/entities/RecipeStatus.kt
> +    draft, published, removed
sim faz

2024-04-12 00:27 UTC, lucascardo12 commented on src/main/resources/application.properties
> +sentry.dsn=https://d66543b55c858858aca35375769efd1d@o4506780583985152.ingest.sentry.io/4506780585426944
sim

2024-04-12 00:27 UTC, merged